name: CI

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - photon-style
      - proton-style
    paths:
      - userChrome.css
      - userContent.css
      - css/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node cache
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Package Install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.1.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
          only_changed: True
          commit_message: "Clean: Prettified Code!"
