on:
  push:
    tags:
      - "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merge master -> photon-style
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: master
          target_branch: photon-style
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master -> proton-style
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: master
          target_branch: proton-style
          github_token: ${{ secrets.GITHUB_TOKEN }}

  upload-files:
    runs-on: ubuntu-latest
    needs: sync-branches
    strategy:
      matrix:
        include:
          - name: "Lepton"
            branch: "master"
          - name: "Lepton-Photon-Style"
            branch: "photon-style"
          - name: "Lepton-Proton-Style"
            branch: "proton-style"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Info file Creation
        run: |
          rm -f LEPTON

          # or BRANCH=$(git rev-parse --abbrev-ref HEAD)
          # or TAGVER=$(git describe --tags --abbrev=0)
          BRANCH=${{ matrix.branch }}
          TAGVER=${GITHUB_REF#refs/*/}

          echo -e "[Info]\nVer=${TAGVER}\nBranch=${BRANCH}" > LEPTON

      - name: Release Structure
        run: |
          mkdir -v chrome

          shopt -s extglob
          mv -v !(chrome|user.js|install.sh) chrome/

          zip -rv ${{ matrix.name }}.zip chrome user.js install.sh

      - uses: softprops/action-gh-release@v1 # actions/create-release, actions/upload-release-asset is deprecated
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ matrix.name }}.zip
