#!/usr/bin/env bash

info=$(cmus-remote -Q 2> /dev/null)

if [ "$?" -ne 0 ]; then
  echo ""
  exit 0
fi

artist=$(echo "$info" | grep "^tag artist " | tail -c +12)
title=$(echo "$info" | grep "^tag title " | tail -c +11)


echo "$icon $artist - $title"
